# Generated by Django 5.2.17 on 2026-09-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_core_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core_userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='core_userprofile',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
