# Generated by Django 5.2.17 on 2026-09-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_activityhistory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityhistory',
            options={'managed': False},
        ),
    ]
