# Generated by Django 5.2.17 on 2026-09-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_core_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile_history',
            name='is_verified',
        ),
    ]
