# Generated by Django 5.2.17 on 2026-09-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_activityhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityhistory',
            options={'managed': True},
        ),
    ]
