# Generated by Django 5.2.17 on 2026-10-05 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile_history',
            name='last_login',
        ),
    ]
