# Generated by Django 5.2.17 on 2026-09-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activityHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_log', models.TextField(max_length=255)),
                ('log_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_activityhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='locationData',
            fields=[
                ('site_id', models.IntegerField(db_column='site_id', primary_key=True, serialize=False)),
                ('site_name', models.CharField(db_column='site_name', max_length=255)),
                ('county', models.CharField(db_column='county', max_length=45)),
            ],
            options={
                'db_table': '"pollutant_data"."location"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pollutant_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('time', models.IntegerField(db_column='time')),
                ('aqi', models.IntegerField(db_column='aqi')),
                ('status', models.CharField(max_length=100)),
                ('so2', models.DecimalField(db_column='so2', decimal_places=2, max_digits=6)),
                ('co', models.DecimalField(db_column='co', decimal_places=2, max_digits=6)),
                ('o3', models.DecimalField(db_column='o3', decimal_places=2, max_digits=6)),
                ('no2', models.DecimalField(db_column='no2', decimal_places=2, max_digits=6)),
                ('nox', models.DecimalField(db_column='nox', decimal_places=2, max_digits=6)),
                ('no', models.DecimalField(db_column='no', decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': '"pollutant_data"."pollutant_values"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='site_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
            ],
        ),
    ]
