# Generated by Django 5.2.17 on 2026-09-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationdata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pollutant_data',
            options={'managed': True},
        ),
    ]
