# Generated by Django 5.2.17 on 2026-09-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_pollutant_data_site_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='activityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_log', models.CharField(max_length=255)),
                ('log_datetime', models.DateTimeField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'firstapp_activityhistory',
                'managed': False,
            },
        ),
    ]
