# Generated by Django 5.2.17 on 2026-09-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_locationdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationdata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pollutant_data',
            options={'managed': False},
        ),
    ]
