# Generated by Django 5.2.17 on 2026-09-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_alter_locationdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_ids',
            old_name='site_id',
            new_name='zipcode',
        ),
    ]
