# Generated by Django 5.2.17 on 2026-09-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_activityhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityhistory',
            options={'managed': True},
        ),
    ]
