# Generated by Django 5.2.17 on 2026-09-01 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_activityhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityhistory',
            options={'managed': False},
        ),
    ]
