# Generated by Django 5.2.17 on 2026-09-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_rename_site_id_site_ids_zipcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='site_ids',
            new_name='zipcode',
        ),
        migrations.AlterModelTable(
            name='locationdata',
            table='"pollutant_data"."locations"',
        ),
    ]
