# Generated by Django 5.2.17 on 2026-09-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_rename_site_ids_zipcode_alter_locationdata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='locationdata',
            table='pollutant_data"."locations',
        ),
        migrations.AlterModelTable(
            name='pollutant_data',
            table='pollutant_data"."pollutant_values',
        ),
    ]
