# Generated by Django 5.2.17 on 2026-09-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_alter_activityhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityhistory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='locationdata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pollutant_data',
            options={'managed': True},
        ),
    ]
