# Generated by Django 5.2.17 on 2026-09-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_alter_activityhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityhistory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='locationdata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pollutant_data',
            options={'managed': False},
        ),
    ]
