# Generated by Django 5.2.17 on 2026-09-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_alter_activityhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activityhistory',
            table='"public"."user_activityhistory"',
        ),
        migrations.AlterModelTable(
            name='locationdata',
            table='"pollutant_data"."location"',
        ),
        migrations.AlterModelTable(
            name='pollutant_data',
            table='"pollutant_data"."pollutant_values"',
        ),
    ]
