# Generated by Django 5.2.17 on 2026-09-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_alter_activityhistory_table_alter_locationdata_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activityhistory',
            table='user_activityhistory',
        ),
    ]
