# Generated by Django 5.2.17 on 2026-09-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0012_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
    ]
