# Generated by Django 5.2.17 on 2026-08-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pollutant_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('time', models.IntegerField(db_column='time')),
                ('aqi', models.IntegerField(db_column='aqi')),
                ('status', models.CharField(max_length=100)),
                ('so2', models.IntegerField(db_column='so2')),
                ('co', models.IntegerField(db_column='co')),
                ('o3', models.IntegerField(db_column='o3')),
                ('no2', models.IntegerField(db_column='no2')),
                ('nox', models.IntegerField(db_column='nox')),
                ('no', models.IntegerField(db_column='no')),
            ],
            options={
                'db_table': 'pollutant_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='site_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
            ],
        ),
    ]
