# Generated by Django 5.2.17 on 2026-10-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locationData',
            fields=[
                ('zipcode', models.IntegerField(db_column='zipcode', primary_key=True, serialize=False, unique=True)),
                ('loc_name', models.CharField(db_column='location_name', max_length=255)),
                ('loc_type', models.CharField(db_column='loc_type', max_length=45)),
            ],
            options={
                'db_table': 'pollutant_data"."locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='pollutant_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('aqi', models.IntegerField(db_column='aqi')),
                ('so2', models.DecimalField(db_column='so2', decimal_places=2, max_digits=6)),
                ('co', models.DecimalField(db_column='co', decimal_places=2, max_digits=6)),
                ('o3', models.DecimalField(db_column='o3', decimal_places=2, max_digits=6)),
                ('pm10', models.DecimalField(db_column='pm10', decimal_places=2, max_digits=6)),
                ('nox', models.DecimalField(db_column='nox', decimal_places=2, max_digits=6)),
                ('aqi_pm25', models.DecimalField(db_column='aqi_pm2.5', decimal_places=2, max_digits=6)),
                ('aqi_pm10', models.DecimalField(db_column='aqi_pm10', decimal_places=2, max_digits=6)),
                ('pm25', models.DecimalField(db_column='pm2.5', decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'pollutant_data"."pollutant_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='zipcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=100)),
            ],
        ),
    ]
